Select *
From Bikes$
Order by Country

---Count Of Gender---
Select Gender, COUNT(Gender) As Number
From Bikes$
Group By Gender

---Count Of Age Group---
Select AgeGroup, COUNT(AgeGroup) As Number
From Bikes$
Group By AgeGroup

---Average Of Buyers Rounded To The Nearest Whole Number---
Select Round(Avg(Customer_Age), 0) As Rounded_Average_Age
From Bikes$


---Total Revenue And Profit By Year---
Select Year, SUM(Revenue) As Revenue, SUM(Profit) As Profit
From Bikes$
Group By Year 
Order By 1

---Average Revenue Per Year---
Select YEAR, AVG(Revenue) As AverageRevenue
From Bikes$
Group By Year
Order By Year

---Looking At Revenue Growth In Percentage---
Select Year, Revenue, (Revenue - LAG(revenue) Over (Order By Year))/LAG(Revenue) Over (Order BY Year)*100 AS Revenue_GRowth_Percentage
From Bikes$
Group By  Year, Revenue

---Profit Margin By Year---
Select Year, Sum(Revenue) AS Revenue, Sum(Profit) AS Profit, (Sum(Profit)/Sum(Revenue))*100 As Margin
From Bikes$
Group By Year
Order By Year


---Average Profit Margin By Year Per Country---
Select Year, Country, Sum(Revenue) AS Revenue, Sum(Profit) AS Profit, (Sum(Profit)/Sum(Revenue))*100 As Margin
From Bikes$
Group By Year, Country
Order By Year

---Revenue By Country Per Year---
Select Country, SUM(Revenue) As Revenue
From Bikes$
Group By Country

---Revenue Generated Per Product Category---
Select Year, Product_Category, SUM(Revenue) As Revenue
From Bikes$
Group By Year, Product_Category
Order By Year

---Looking At Product Category That Generates The Most Revenue---
Select Product_Category, SUM(Revenue) As Revenue
From Bikes$
Group BY Product_Category
Order By 2 Desc

---Looking At Revenue Generated By A Specific Country---
Select Year, Country, SUM(Revenue) As Revenue
From Bikes$
Where Country = 'Germany'
Group By Year, Country
Order By Year

---Orders Per Product---
Select Product, SUM(Order_Quantity) OrderQuantity
From Bikes$
Group By Product
Order By 2 Desc

---Revenue Generated By Each Product---
Select Product, SUM(Revenue) Revenue
From Bikes$
Group By Product
Order By 2 Desc
